import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const prototype=readFileSync(new URL('../prototype/mamoken_prototype_v01.html',import.meta.url),'utf8');
const dist=readFileSync(new URL('../dist/mamoken_mobile.html',import.meta.url),'utf8');

assert.ok(prototype.includes('/* T22 character detail panel */'));
assert.ok(prototype.includes('<script src="../runtime/character-catalog-browser.js"></script>'));
assert.ok(prototype.includes("if(game.screen==='characterDetail'){characterDetailPress(p);return null;}"));
assert.ok(prototype.includes("else if(game.screen==='characterDetail')rCharacterDetail();"));
assert.ok(prototype.includes("{id:'performance',label:'性能'}"));
assert.ok(prototype.includes("{id:'moves',label:'わざ'}"));
assert.ok(prototype.includes("{id:'combos',label:'コンボ'}"));
assert.ok(prototype.includes("txt('性能・わざ・コンボを見る'"));
assert.ok(prototype.includes("txt('キャラ選択へもどる'"));
assert.ok(prototype.includes("txt('コンボは全枠 未検証'"));
assert.ok(prototype.includes("txt('入力列: 未確定'"));
assert.ok(prototype.includes("return '実装済み'"));
assert.ok(prototype.includes("return '設計確定・未実装'"));
assert.ok(prototype.includes("return '候補'"));
assert.ok(prototype.includes("move.attribute+' / Reach '"));
assert.ok(prototype.includes("'条件: '+move.conditionsJa.join('／')"));
assert.ok(prototype.includes("c.roar.nameJa"));
assert.ok(prototype.includes("c.ultimate.nameJa"));
assert.ok(prototype.includes("c.cpuPlanJa"));
assert.ok(prototype.includes("characterDetailScroll=Math.min(characterDetailMaxScroll,characterDetailScroll+260)"));
assert.ok(prototype.includes("characterDetailScroll=Math.max(0,characterDetailScroll-260)"));
assert.ok(prototype.includes("sfx('tap');game.screen='select';return;"));
// pre-existing fix, unrelated to BAL-R1: P1でselected.playable→selected.onlinePlayableへ改名され
// 文言も「正式実装・オフラインのみ」に変わったが、このテストの期待文字列が追従していなかったため合わせる
assert.ok(prototype.includes("selected.onlinePlayable?'正式実装・オンライン可':'正式実装・オフラインのみ'"));

const detailButton=/const SELECT_DETAIL_BTN=\{x:18,y:478,w:W-36,h:(\d+)\}/.exec(prototype);
const backButton=/const CHARACTER_DETAIL_BACK_BTN=\{x:20,y:872,w:W-40,h:(\d+)\}/.exec(prototype);
const tabHeight=/return\{x:20\+i\*\(w\+gap\),y:108,w:w,h:(\d+)\}/.exec(prototype);
assert.ok(detailButton&&Number(detailButton[1])>=70);
assert.ok(backButton&&Number(backButton[1])>=74);
assert.ok(tabHeight&&Number(tabHeight[1])>=74);

const inputStart=prototype.indexOf('function characterDetailPress(p){');
const inputEnd=prototype.indexOf('function resultPress(p){',inputStart);
const detailInput=prototype.slice(inputStart,inputEnd);
assert.ok(detailInput.includes("game.screen='select'"));
assert.equal(detailInput.includes('selCharIdx='),false,'closing details must preserve selected character');
assert.equal(detailInput.includes('startBattle'),false,'detail screen must not start battles');

const selectStart=prototype.indexOf('function selectPress(p){');
const selectEnd=prototype.indexOf('function characterDetailPress(p){',selectStart);
const selectInput=prototype.slice(selectStart,selectEnd);
assert.ok(selectInput.includes("if(i>=ROSTER.length){sfx('guard');return;}"));
assert.ok(selectInput.includes("if(!selected.trialPlayable){sfx('guard');return;}"));
assert.ok(selectInput.includes('openCharacterDetail()'));
assert.ok(selectInput.includes('game.p1=selected.combatIndex'));
assert.ok(selectInput.includes('Math.random()*CHARS.length'));

for(const name of ['モグゾー','ピスケ','ゴダン','ハクマ','チルカ','タキマル','ヨミカゲ','バレット','ダークモグゾー']){
  assert.ok(dist.includes(name),`dist missing roster detail content: ${name}`);
}
assert.equal(dist.includes('<script src="../runtime/character-catalog-browser.js"></script>'),false,'single-file dist must inline browser catalog');
assert.ok(dist.includes('Generated by tools/build_character_catalog_browser.mjs'));
assert.ok(dist.includes('/* T22 character detail panel */'));
assert.ok(dist.includes('/* T28 roster trial select UI */'));
assert.ok(dist.includes("const CHARACTER_DETAIL_CATALOG=window.__MAMOKEN_CHARACTER_CATALOG__||null;"));

function compileInlineScripts(html,label){
  const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)]
    .filter((match)=>!match[0].includes(' src='))
    .map((match)=>match[1]);
  assert.ok(scripts.length>0,`${label}: no inline scripts`);
  for(let i=0;i<scripts.length;i++)assert.doesNotThrow(()=>new Function(scripts[i]),`${label}: script ${i} syntax`);
}
compileInlineScripts(prototype,'prototype');
compileInlineScripts(dist,'dist');

for(const forbidden of ['localStorage.setItem','sessionStorage.setItem','fetch("','XMLHttpRequest(','new WebSocket(']){
  assert.equal(detailInput.includes(forbidden),false,`detail input forbidden side effect: ${forbidden}`);
}
console.log('character detail panel tests passed; tabs=3; roster=9; offlineTrial=9; selection-preserved=true; dist-inline=true');