import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import {
  CHARACTER_CATALOG,
  CHARACTER_CATALOG_VERSION,
  hashCharacterCatalog,
} from '../src/core/character-catalog.ts';

const source=readFileSync(new URL('../runtime/character-catalog-browser.js',import.meta.url),'utf8');
const context=vm.createContext({window:{}});
vm.runInContext(source,context,{filename:'character-catalog-browser.js'});
const api=context.window.__MAMOKEN_CHARACTER_CATALOG__;

assert.ok(api);
assert.equal(api.version,CHARACTER_CATALOG_VERSION);
assert.equal(api.hash,hashCharacterCatalog());
assert.equal(api.characters.length,9);
assert.equal(api.characters.reduce((sum,character)=>sum+character.moves.length,0),63);
assert.equal(JSON.stringify(api.characters),JSON.stringify(CHARACTER_CATALOG));
assert.deepEqual(Object.keys(api.byId).sort(),CHARACTER_CATALOG.map((character)=>character.id).sort());
assert.equal(api.byId.moguzo.moves[0].nameJa,'地走り');
assert.equal(api.byId.dark_moguzo.moves[6].nameJa,'黒煙突き');

assert.equal(Object.isFrozen(api),true);
assert.equal(Object.isFrozen(api.characters),true);
assert.equal(Object.isFrozen(api.characters[0]),true);
assert.equal(Object.isFrozen(api.characters[0].moves),true);
assert.equal(Object.isFrozen(api.byId),true);
const originalName=api.byId.moguzo.nameJa;
try{api.byId.moguzo.nameJa='改変';}catch{}
assert.equal(api.byId.moguzo.nameJa,originalName);
try{api.characters.push({});}catch{}
assert.equal(api.characters.length,9);

const descriptor=Object.getOwnPropertyDescriptor(context.window,'__MAMOKEN_CHARACTER_CATALOG__');
assert.equal(descriptor.writable,false);
assert.equal(descriptor.configurable,false);
assert.equal(descriptor.enumerable,false);

for(const forbidden of ['localStorage','sessionStorage','fetch(','XMLHttpRequest','WebSocket','navigator.','document.cookie','Date.now','performance.now','Math.random']){
  assert.equal(source.includes(forbidden),false,`forbidden browser catalog API: ${forbidden}`);
}
assert.ok(source.startsWith('/* Generated by tools/build_character_catalog_browser.mjs. Do not hand-edit. */'));
console.log(`character catalog browser tests passed; characters=9; moves=63; hash=${api.hash}; frozen=true`);
