#!/usr/bin/env node
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CHARACTER_CATALOG,
  CHARACTER_CATALOG_VERSION,
  hashCharacterCatalog,
  validateCharacterCatalog,
} from '../src/core/character-catalog.ts';
import {
  buildCore3CommandCatalogContract,
  hashCore3CommandCatalog,
  validateCore3CommandCatalog,
} from '../src/core/command-catalog.ts';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const OUT=path.join(ROOT,'runtime','character-catalog-browser.js');

validateCharacterCatalog();
validateCore3CommandCatalog();

const commandContract=buildCore3CommandCatalogContract();
const payload={
  version:CHARACTER_CATALOG_VERSION,
  hash:hashCharacterCatalog(),
  characters:CHARACTER_CATALOG,
  commandContract:{
    ...commandContract,
    hash:hashCore3CommandCatalog(commandContract),
  },
};

const source=`/* Generated by tools/build_character_catalog_browser.mjs. Do not hand-edit. */
(function installMamokenCharacterCatalog(global){
  'use strict';
  const payload=${JSON.stringify(payload)};
  function deepFreeze(value){
    if(!value||typeof value!=='object'||Object.isFrozen(value))return value;
    Object.freeze(value);
    for(const key of Object.keys(value))deepFreeze(value[key]);
    return value;
  }
  const byId=Object.create(null);
  for(const character of payload.characters)byId[character.id]=character;
  const api=deepFreeze({
    version:payload.version,
    hash:payload.hash,
    characters:payload.characters,
    byId:byId,
    commandContract:payload.commandContract,
  });
  Object.defineProperty(global,'__MAMOKEN_CHARACTER_CATALOG__',{
    value:api,
    writable:false,
    configurable:false,
    enumerable:false,
  });
})(typeof window!=='undefined'?window:globalThis);
`;

mkdirSync(path.dirname(OUT),{recursive:true});
writeFileSync(OUT,source,'utf8');
console.log(`runtime/character-catalog-browser.js generated; characters=${payload.characters.length}; characterHash=${payload.hash}; commandHash=${payload.commandContract.hash}`);