#!/usr/bin/env node
// マモ拳（仮） 闘技場(昼)BGMのbase64ペイロード生成スクリプト。
//
// file://直開き(prototype)ではfetch()/XMLHttpRequestでのmp3バイト列取得がCORSで
// 失敗する(<script src>や<audio src>のような通常のリソース読み込みとは異なる制限)。
// 闘技場(昼)BGMはWeb Audio API(AudioBufferSourceNode.loopStart)で intro+loop を
// 実現する必要があり、decodeAudioData()にはArrayBufferが要る。そこで
// assets/bgm/bgm_village_arena_day.mp3 をbase64化してruntime/arena-bgm-b64.jsへ
// 書き出し、<script src>(=CORS制限を受けない読み込み経路)経由でwindowへ載せる。
//
// 再生成手順: 音源(assets/bgm/bgm_village_arena_day.mp3)を差し替えたら
//   node tools/build_arena_bgm_b64.mjs
// を再実行し、runtime/arena-bgm-b64.jsの再生成もあわせてコミットすること。
//
// dist(mamoken_mobile.html)では同じ音源が既にbuild_mobile.mjsによって
// __ASSET_MAP__のdata URLとして埋め込まれるため、このファイルはdist側では不要
// (build_mobile.mjsが<script src>タグ自体を除去する)。

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'assets', 'bgm', 'bgm_village_arena_day.mp3');
const OUT = path.join(ROOT, 'runtime', 'arena-bgm-b64.js');

const buf = readFileSync(SRC);
const b64 = buf.toString('base64');

const source = `/* Generated by tools/build_arena_bgm_b64.mjs from assets/bgm/bgm_village_arena_day.mp3.
   Do not hand-edit. */
window.__ARENA_BGM_B64__=${JSON.stringify(b64)};
`;

writeFileSync(OUT, source, 'utf8');
console.log(`runtime/arena-bgm-b64.js を生成しました (原本: ${buf.length}バイト / base64: ${b64.length}文字)`);
