#!/usr/bin/env node
// vNext PR1: connects data/art/ability_ui_manifest.json (curated ability UI/gauge/VFX
// assets) into the browser runtime as a static global, the same pattern already used
// for the current-art manifest. Presentation-only: this never reads or writes BAL,
// combat state, or hit/reach/hurt boxes -- it only resolves and validates asset paths.
// Actual per-character trigger wiring (when to show which icon/gauge/VFX) belongs to
// the vNext PR4 ability state machines; this PR only guarantees every referenced asset
// exists and is reachable from a stable global for that future wiring to consume.

import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MANIFEST_PATH = path.join(ROOT, 'data', 'art', 'ability_ui_manifest.json');
const OUTPUT_PATH = path.join(ROOT, 'runtime', 'ability-ui-manifest-browser.js');

function collectPaths(node, root, found) {
  if (!node || typeof node !== 'object') return;
  if (typeof node.path === 'string' || (typeof node === 'string' && node.includes('/'))) {
    const relPath = typeof node === 'string' ? node : node.path;
    if (relPath) found.add(path.join(root, relPath));
    return;
  }
  for (const value of Object.values(node)) {
    if (typeof value === 'string' && (value.startsWith('icon/') || value.startsWith('gauge/') || value.startsWith('vfx/'))) {
      found.add(path.join(root, value));
    } else if (value && typeof value === 'object') {
      collectPaths(value, root, found);
    }
  }
}

export function buildAbilityUiManifest() {
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));
  const absRoot = path.resolve(ROOT, manifest.root);
  const found = new Set();
  collectPaths(manifest.characters, absRoot, found);
  collectPaths(manifest.common, absRoot, found);
  if (found.size === 0) throw new Error('ability_ui_manifest.json resolved zero asset paths');
  for (const absPath of found) {
    if (!existsSync(absPath)) throw new Error(`missing ability UI asset: ${path.relative(ROOT, absPath)}`);
    if (statSync(absPath).size === 0) throw new Error(`empty ability UI asset: ${path.relative(ROOT, absPath)}`);
  }
  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  const browserSource = [
    '/* Generated by tools/build_ability_ui_manifest.mjs. Do not edit by hand. */',
    `globalThis.MAMOKEN_ABILITY_UI_MANIFEST=${JSON.stringify(manifest)};`,
    '',
  ].join('\n');
  writeFileSync(OUTPUT_PATH, browserSource);
  return { manifest, verifiedAssetCount: found.size };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { verifiedAssetCount } = buildAbilityUiManifest();
  console.log(`ability UI manifest connected: verifiedAssetCount=${verifiedAssetCount}`);
}
