#!/usr/bin/env node
// マモ拳（仮） BGM-R1.2: 全BGM(タイトル/選択/闘技場)のbase64ペイロード生成スクリプト。
//
// file://直開き(prototype)ではfetch()/XMLHttpRequestでのmp3バイト列取得がCORSで
// 失敗する(<script src>や<audio src>のような通常のリソース読み込みとは異なる制限)。
// BGM-R1.2で全BGMをWeb Audio API(AudioBufferSourceNode)経由の再生に統一したため、
// decodeAudioData()に渡すArrayBufferが全曲分必要になった。そこでassets/bgm/配下の
// 各mp3をbase64化してruntime/bgm-b64.jsへ書き出し、<script src>(=CORS制限を受けない
// 読み込み経路)経由でwindow.__BGM_B64__へ載せる。
//
// (旧tools/build_arena_bgm_b64.mjs/runtime/arena-bgm-b64.jsを置き換える。
//  闘技場BGM専用の単一文字列ではなく、全曲分をキー付きで持つ辞書形式にした)
//
// 再生成手順: assets/bgm/配下の音源を差し替えたら
//   node tools/build_bgm_b64.mjs
// を再実行し、runtime/bgm-b64.jsの再生成もあわせてコミットすること。
// 新曲を追加する場合はBGM_SOURCESの配列にファイル名を追記する。
//
// dist(mamoken_mobile.html)では同じ音源が既にbuild_mobile.mjsによって
// __ASSET_MAP__のdata URLとして埋め込まれるため、このファイルはdist側では不要
// (build_mobile.mjsが<script src>タグ自体を除去する)。

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BGM_DIR = path.join(ROOT, 'assets', 'bgm');
const OUT = path.join(ROOT, 'runtime', 'bgm-b64.js');

// キー: prototype側のBGM_SOURCESと一致させること
const BGM_SOURCES = {
  title: 'bgm_title_marmot_fist.mp3',
  select: 'bgm_character_select.mp3',
  arena: 'bgm_village_arena_day.mp3',
};

const entries = {};
let totalRaw = 0, totalB64 = 0;
for (const [key, filename] of Object.entries(BGM_SOURCES)) {
  const buf = readFileSync(path.join(BGM_DIR, filename));
  const b64 = buf.toString('base64');
  entries[key] = b64;
  totalRaw += buf.length;
  totalB64 += b64.length;
  console.log(`${key}: ${filename} (${buf.length}バイト → base64 ${b64.length}文字)`);
}

const source = `/* Generated by tools/build_bgm_b64.mjs from assets/bgm/*.mp3.
   Do not hand-edit. */
window.__BGM_B64__=${JSON.stringify(entries)};
`;

writeFileSync(OUT, source, 'utf8');
console.log(`runtime/bgm-b64.js を生成しました (原本合計: ${totalRaw}バイト / base64合計: ${totalB64}文字)`);
